<!-- title: "Tables" -->

<!-- format: -->
<!--   docx: -->
<!--     reference-doc: reference_document.docx -->

<!-- link-citations: true -->
<!-- linkcolor: blue -->

<!-- editor_options: -->
<!--   chunk_output_type: console -->

<!-- execute: -->
<!--   echo: false -->
<!--   warning: false -->
<!--   error: false -->
<!--   message: false -->

```{r}
here::i_am("output/paper/_tables.qmd")
```

# Tables for descriptive data

## Study populations

```{r pop-desc}
#| label: tbl-pop-desc
#| tbl-cap: Characteristics of the children included in the analyses, by cohort and overall

targets::tar_load("table1", store = store)
table1
```

## Endocrine disruptors

```{r edc-desc}
#| label: tbl-edc-desc
#| tbl-cap: Levels of unprocessed chemicals, by cohort and overall

targets::tar_load("desc_chems_mets", store = store)
desc_chems_mets$desc_chems
```

## Corticosteroids

```{r met-desc}
#| label: tbl-met-desc
#| tbl-cap: Levels of unprocessed corticosteroids, by cohort and overall

desc_chems_mets$desc_mets
```

# Tables for main results

## Balancing weights

```{r}
targets::tar_load(
  dplyr::matches("balance_(\\d)$"),
  store = store
)
```

```{r balance-1}
#| label: tbl-balance-1
#| tbl-cap: Effective sample size before and after weights estimation for $hitrtse ~ edc$

balance_1 |>
  tidylog::group_by(class) |>
  dplyr::arrange(dplyr::desc(Adjusted)) |>
  tidylog::ungroup() |>
  gt::gt(groupname_col = "class") |>
  gt::fmt_number(n_sigfig = 4) |>
  gt::tab_footnote(
    footnote = "N.",
    locations = gt::cells_column_labels(
      columns = c(Unadjusted, Adjusted)
    )
  ) |>
  gt::tab_footnote(
    footnote = "Truncated weights.",
    locations = gt::cells_column_labels(columns = Adjusted)
  )
```

```{r balance-2}
#| label: tbl-balance-2
#| tbl-cap: Effective number of observations

balance_2 |>
  tidylog::group_by(class) |>
  dplyr::arrange(dplyr::desc(Adjusted)) |>
  tidylog::ungroup() |>
  gt::gt(groupname_col = "class") |>
  gt::fmt_number(n_sigfig = 4) |>
  gt::tab_footnote(
    footnote = "N.",
    locations = gt::cells_column_labels(
      columns = c(Unadjusted, Adjusted)
    )
  ) |>
  gt::tab_footnote(
    footnote = "Truncated weights.",
    locations = gt::cells_column_labels(columns = Adjusted)
  )
```

```{r balance-3}
#| label: tbl-balance-3
#| tbl-cap: Effective number of observations

balance_3 |>
  dplyr::arrange(dplyr::desc(Adjusted)) |>
  gt::gt() |>
  gt::fmt_number(n_sigfig = 4) |>
  gt::tab_footnote(
    footnote = "N.",
    locations = gt::cells_column_labels(
      columns = c(Unadjusted, Adjusted)
    )
  ) |>
  gt::tab_footnote(
    footnote = "Truncated weights.",
    locations = gt::cells_column_labels(columns = Adjusted)
  )
```

```{r}
targets::tar_load(
  dplyr::matches("weights_(\\d)$"),
  store = store
)
```

```{r weights-1}
#| label: tbl-weights-1
#| tbl-cap: Weights

tidy_res_weighted_fits(
  dat_tbl = weights_1$dat_tbl,
  dat_plt = weights_1$dat_plt,
  sa_var = NULL
)$table
```

```{r weights-2}
#| label: tbl-weights-2
#| tbl-cap: Weights

tidy_res_weighted_fits(
  dat_tbl = weights_2$dat_tbl,
  dat_plt = weights_2$dat_plt,
  sa_var = NULL
)$table
```

```{r weights-3}
#| label: tbl-weights-3
#| tbl-cap: Weights

tidy_res_weighted_fits(
  dat_tbl = weights_3$dat_tbl,
  dat_plt = weights_3$dat_plt,
  sa_var = NULL
)$table
```

## Marginal comparisons

```{r}
targets::tar_load(
  dplyr::matches("marginal_comparisons_(\\d)$"),
  store = store
)
```

```{r marginal-1}
#| label: tbl-marginal-1
#| tbl-cap: Average comparisons

tidy_res_meffects(
  df = marginal_comparisons_1,
  sa_var = NULL,
  which_res = "comparisons",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$table
```

```{r marginal-2}
#| label: tbl-marginal-2
#| tbl-cap: Average comparisons

tidy_res_meffects(
  df = marginal_comparisons_2,
  sa_var = NULL,
  which_res = "comparisons",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$table
```

```{r marginal-3}
#| label: tbl-marginal-3
#| tbl-cap: Average comparisons

tidy_res_meffects(
  df = marginal_comparisons_3,
  sa_var = NULL,
  which_res = "comparisons",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$table
```

# Other analyses

## Marginal hypothesis

```{r}
targets::tar_load(
  dplyr::matches("marginal_hypothesis_(\\d)SA$"),
  store = store
)
```

```{r hypothesis-1}
#| label: tbl-hypothesis-1
#| tbl-cap: Hypothesis testing for effect modification

tidy_res_meffects(
  df = marginal_hypothesis_1SA,
  sa_var = "e3sex",
  which_res = "hypothesis",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$table
```

```{r hypothesis-2}
#| label: tbl-hypothesis-2
#| tbl-cap: Hypothesis testing for effect modification

tidy_res_meffects(
  df = marginal_hypothesis_2SA,
  sa_var = "e3sex",
  which_res = "hypothesis",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$table
```

```{r hypothesis-3}
#| label: tbl-hypothesis-3
#| tbl-cap: Hypothesis testing for effect modification

tidy_res_meffects(
  df = marginal_hypothesis_3SA,
  sa_var = "e3sex",
  which_res = "hypothesis",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$table
```
