---
title: "Childhood exposure to non-persistent endocrine disruptors, glucocorticosteroids, and neurodevelopment: A study based on the parametric g-formula"

metadata-files:
  - ../../docs/authors.yml

format:
  html:
    embed-resources: true

link-citations: true
linkcolor: blue

editor_options:
  chunk_output_type: console
---

```{r}
proc_one <- function(df, idx) {
  tmp <- df$authors[[idx]]
  
  affiliations <- unname(unlist(tmp$affiliations))
  full_names <- tibble::tibble(
    id = unlist(lapply(df$affiliations, "[[", "id")),
    long = unlist(lapply(df$affiliations, "[[", "name"))
  ) |>
    dplyr::mutate(
      long = stringr::str_replace_all(
        long, "\n", ""
      )
    )
  affiliations_long <- unlist(lapply(
    affiliations,
    function(x) {
      full_names[full_names$id == x, ]$long
    }
  ))
  affiliations_long <- paste0(affiliations_long, collapse = ".<br>")
  
  ret <- tibble::tribble(
    ~name, ~affiliations, ~role,
    tmp$name, affiliations_long, paste0(tmp$role, collapse = "<br>")
  )
}
```

```{r}
authors <- yaml::read_yaml("../../docs/authors.yml")
lapply(seq_along(authors$authors), function(x) {
  proc_one(authors, x)
}) |>
  dplyr::bind_rows() |>
  gt::gt() |>
  gt::fmt_markdown(columns = dplyr::everything()) |>
  gt::gtsave("authors.pdf")
```
