---
title: "Figures"

format:
  pdf:
    pdf-engine: lualatex
    number-sections: true
    toc: false
    include-in-header:
      text: |
        \usepackage{lineno}
        \usepackage{rotating}
        \usepackage{float}
        \usepackage{typearea}
    include-before-body:
      text: |
        \linenumbers

link-citations: true
linkcolor: blue

editor_options: 
  chunk_output_type: console

execute:
  echo: false
  warning: false
  error: false
  message: false
---

```{r}
here::i_am("output/paper/figures.qmd")
```

```{r vars}
source(here::here("code/dictionaries.R"))
source(here::here("code/data.R"))
source(here::here("code/proc_res.R"))

is_hpc <- FALSE
store <- ifelse(
  is_hpc, 
  paste0(
    "/PROJECTES/HELIX_OMICS/DATA_PREVIOUS_MIGRATION/",
    "lorenzoF/data/data_paper3/_targets/_targets_res"
  ), 
  "~/mounts/rstudioserver/data/data_paper3/_targets/_targets_res"
)

id_var <- "HelixID"
num_digits_est = 3
num_digits_sig = 2
params <- params(is_hpc = is_hpc)
threshold_within_lod <- params$steps$rq2$preproc_outcome$llodq$threshold_within
threshold_overall_lod <- params$steps$rq2$preproc_outcome$llodq$threshold_overall
threshold_within_nan <- params$steps$rq2$preproc_outcome$missings$threshold_within
threshold_overall_nan <- params$steps$rq2$preproc_outcome$missings$threshold_overall
knn_k <- params$steps$rq2$preproc_outcome$missings$k
```

- Figure titles and legends should be submitted as single paragraph.

# Main results

## Marginal comparisons

```{r}
targets::tar_load(
  dplyr::matches("marginal_comparisons_(\\d)$"),
  store = store
)
```

```{r marginal-1}
#| label: fig-marginal-1
#| fig-cap: Average comparisons
#| fig-width: 6
#| fig-height: 7

tidy_res_meffects(
  df = marginal_comparisons_1,
  sa_var = NULL,
  which_res = "comparisons",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$plot
```

```{r marginal-2}
#| label: fig-marginal-2
#| fig-cap: Average comparisons
#| fig-width: 9
#| fig-height: 10

tidy_res_meffects(
  df = marginal_comparisons_2,
  sa_var = NULL,
  which_res = "comparisons",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$plot
```

```{r marginal-3}
#| label: fig-marginal-3
#| fig-cap: Average comparisons
#| fig-width: 5
#| fig-height: 5

tidy_res_meffects(
  df = marginal_comparisons_3,
  sa_var = NULL,
  which_res = "comparisons",
  num_digits_est = num_digits_est,
  num_digits_sig = num_digits_sig
)$plot
```
