---
title: "Estimating associations between childhood exposure to non-persistent endocrine disruptors, corticosteroids, and neurodevelopment: A study based on the parametric g-formula"

# metadata-files:
#   - ../../../../all_phd/authors.yml

format:
  docx:
    reference-doc: reference_document.docx
  pdf:
    pdf-engine: lualatex
    number-sections: true
    toc: false
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{lineno}
        \usepackage{rotating}
        \usepackage{float}
        \usepackage{typearea}
    include-before-body:
      text: |
        \linenumbers

bibliography: bibliography.bib
csl: ama11.csl

link-citations: true
linkcolor: blue

filters:
  - acronyms
  # - authors-block
  - ../../../../all_phd/_extensions/wordcount/citeproc.lua
  - ../../../../all_phd/_extensions/wordcount/wordcount.lua

acronyms:
  fromfile: ../../../../all_phd/acronyms.yml
  insert_links: false
  insert_loa: false
  sorting: alphabetical

editor_options: 
  chunk_output_type: console

execute:
  echo: false
  warning: false
  error: false
  message: false
---

# Abstract {.unnumbered}

\newpage

- Authorship must follow the ICMJE's criteria. Author names should be listed in ScholarOne and author contributions should be detailed in the cover letter ("Author A..."). Neither names nor contributions should appear in the blinded manuscript. Do not include conflicts of interest.
- The use of the word "effect(s)" as a proxy for "association(s)" is discouraged.
- The length of the abstract must be less or equal than 200 words, and should be unstructured, stating the research questions, the methods used, and the results and conclusions of the research.
- The length must be <4,000 words, excluding abstract, references, tables, figure captions, acknowledgments, and Supplementary Material.
  - In-text citations: full-sized Arabic numerals in parentheses within the sentence.
- Submission: SER members receive a 10% discount on the fees per page. This should be requested in the cover letter. Also 20% discount for Open Access charges. If uploading a single file (document, tables, figures, SM), designate the file as "Main document - anonymous".

{{< include sections/introduction.qmd >}}

# Methods {#sec-methods}

{{< include sections/methods.qmd >}}

# Results {#sec-res}

{{< include sections/results.qmd >}}

# Discussion {#sec-discussion}

{{< include sections/discussion.qmd >}}

\newpage

# Funding

\newpage

# References {.unnumbered}

::: {#refs}
:::
